Repository WildCodeSchool/orleans-php-202103-project-voyante, pull requests merged in 2021-04, with the labels that each got.

#3 initialisation
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Corrections done, reviewed

#38 S1_US1_Navbar
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/fond-medium-navbar.png
  public/assets/images/telephone.png
  public/assets/images/voyance-2.png
  src/View/Home/index.html.twig
  src/View/component/_navbar.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed

#54 S1_US1_add h1 to Navbar
  public/assets/css/navbar.css
  src/View/component/_navbar.html.twig
Labels: Corrections done, Reviewed

#35 S1 us8 accueil
  public/assets/css/indexHome.css
  public/assets/css/style.css
  public/assets/images/favicon.png
  public/assets/images/favicon_old.png
  public/assets/images/home/42ans.webp
  public/assets/images/home/LOGO.webp
  public/assets/images/home/purple_nebula.webp
  public/assets/images/story/photo_nathalie2.webp
  src/View/Home/_home.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed, conflicts resolved

#53 S01 us4 prestations html css
  public/assets/css/prestations.css
  public/assets/css/style.css
  src/View/Home/_prestations.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed, conflicts resolved

#56 Devupdate
  public/assets/css/indexHome.css
  public/assets/css/style.css
  public/assets/images/home/purple_nebula.webp
  src/View/Home/index.html.twig
  src/View/component/_navbar.html.twig
Labels: Reviewed

#41 S1_US2_footer
  public/assets/css/footer.css
  src/View/Home/index.html.twig
  src/View/component/_footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed, conflicts resolved

#42 S1 us3 story
  public/assets/css/indexStory.css
  public/assets/css/style.css
  public/assets/images/story/photo_nathalie2.webp
  src/View/Home/_story.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: conflicts resolved, review requested

#59 Devupdate v2
  public/assets/css/indexHome.css
  public/assets/css/indexStory.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/telephone.png
  src/View/Home/_story.html.twig
  src/View/Home/index.html.twig
  src/View/component/_navbar.html.twig
Labels: Corrections done, Reviewed

#61 First pull request dev to master
  public/assets/css/footer.css
  public/assets/css/indexHome.css
  public/assets/css/indexStory.css
  public/assets/css/navbar.css
  public/assets/css/prestations.css
  public/assets/css/style.css
  public/assets/css/testimony.css
  public/assets/images/592367.jpg
  public/assets/images/favicon.png
  public/assets/images/favicon_old.png
  public/assets/images/fond-medium-navbar.png
  public/assets/images/home/42ans.webp
  public/assets/images/home/LOGO.webp
  public/assets/images/home/purple_nebula.webp
  public/assets/images/story/photo_nathalie2.webp
  public/assets/images/telephone.png
  public/assets/images/voyance-2.png
  src/View/Home/_carousel.html.twig
  src/View/Home/_home.html.twig
  src/View/Home/_prestations.html.twig
  src/View/Home/_story.html.twig
  src/View/Home/index.html.twig
  src/View/component/_footer.html.twig
  src/View/component/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#64 correcting links
  src/View/Home/_home.html.twig
  src/View/Home/_story.html.twig
  src/View/component/_navbar.html.twig
Labels: Reviewed

#63 coorecting shadow on Home
  public/assets/css/style.css
Labels: Reviewed

#62 correcting responsive
  public/assets/css/prestations.css
Labels: Reviewed

#65 Patching
  public/assets/css/prestations.css
  public/assets/css/style.css
  src/View/Home/_home.html.twig
  src/View/Home/_story.html.twig
  src/View/component/_navbar.html.twig
Labels: Reviewed

#57 S2 us3 view story
  public/assets/css/history/indexHistory.css
  public/assets/css/style.css
  public/assets/images/favicon_old.png
  public/assets/images/history/30ans.webp
  public/assets/images/history/42ans.jpg
  public/assets/images/history/8ans.webp
  public/assets/images/history/9-20ans.webp
  src/Controller/HomeController.php
  src/View/History/index.html.twig
  src/View/Home/_story.html.twig
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed

#82 add AdminController.php
  src/Controller/AdminController.php
Labels: Reviewed

#80 removing all @import style.css on css files
  public/assets/css/footer.css
  public/assets/css/indexHome.css
  public/assets/css/navbar.css
  public/assets/css/prestations.css
  public/assets/css/testimony.css
Labels: Reviewed

#79 S02_US5_BDD
  testimony.sql
Labels: Reviewed

#77 S3_formValidateService
  src/Service/FormValidation.php
Labels: Reviewed

#81 create admin view infrastucture
  src/View/Admin/Home/Component/_admin_navbar.html.twig
  src/View/Admin/Home/index.html.twig
  src/View/Admin/admin_layout.html.twig
Labels: Corrections done, Reviewed

#84 updating HomeController to adapt to Visitor structur
  src/Controller/HomeController.php
Labels: Reviewed

#83 create Visitor Structur
  src/View/Visitor/Home/Component/_carousel.html.twig
  src/View/Visitor/Home/Component/_footer.html.twig
  src/View/Visitor/Home/Component/_home.html.twig
  src/View/Visitor/Home/Component/_navbar.html.twig
  src/View/Visitor/Home/Component/_prestations.html.twig
  src/View/Visitor/Home/Component/_story.html.twig
  src/View/Visitor/Home/index.html.twig
  src/View/Visitor/layout.html.twig
  src/View/base_layout.html.twig
Labels: Reviewed

#78 S02_US4 - View Training
  public/assets/css/services.css
  public/assets/css/style.css
  public/assets/css/training.css
  public/assets/images/culture.jpg
  public/assets/images/esprits.jpg
  public/assets/images/magie.jpg
  public/assets/images/protection.jpg
  src/Controller/HomeController.php
  src/Controller/TrainingController.php
  src/View/Home/_services.html.twig
  src/View/Home/index.html.twig
  src/View/Training/index.html.twig
Labels: Reviewed

#43 S1 us6 formulaire
  public/assets/css/contact.css
  public/assets/css/style.css
  public/assets/css/success.css
  src/Controller/ContactController.php
  src/View/Contact/contact.html.twig
  src/View/Contact/success.html.twig
Labels: Corrections done, Reviewed

#85 remove old structur files
  src/View/component/_footer.html.twig
  src/View/component/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#86 Replace Prestations by Services
  src/View/Visitor/Home/Component/_prestations.html.twig
  src/View/Visitor/Home/Component/_services.html.twig
  src/View/Visitor/Home/index.html.twig
Labels: Reviewed

#98 fixing dev bugs
  public/assets/css/services.css
  src/View/Visitor/Home/index.html.twig
  src/View/Visitor/layout.html.twig
Labels: Reviewed

#97 creation testimony manager
  src/Model/TestimoniesManager.php
Labels: Reviewed

#96 Us13 adm testi manager insert
  src/Model/TestimoniesManager.php
Labels: Reviewed

#101 patch dev to update to visitor structure
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/Controller/TrainingController.php
  src/View/Visitor/Contact/contact.html.twig
  src/View/Visitor/Contact/success.html.twig
  src/View/Visitor/History/index.html.twig
  src/View/Visitor/Home/Component/_footer.html.twig
  src/View/Visitor/Home/Component/_navbar.html.twig
  src/View/Visitor/Training/index.html.twig
  src/View/base_layout.html.twig
Labels: Reviewed

#105 Us13 testimanager update v2
  src/Model/TestimoniesManager.php
Labels: Reviewed

#91 Us13 adm testi controller add
  src/Controller/TestimoniesController.php
Labels: Reviewed, conflicts resolved

#107 add parents to success.html.twig
  src/View/Visitor/Contact/success.html.twig
Labels: Reviewed

#106 US13 database testimony sql
  testimony.sql
Labels: Reviewed

#104 remove Obsolet View/Home
  src/View/Home/_carousel.html.twig
  src/View/Home/_home.html.twig
  src/View/Home/_story.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#103 remove white lign in history view
  public/assets/css/history/indexHistory.css
Labels: Reviewed

#93 Us13 adm testi controller show
  src/Controller/TestimoniesController.php
Labels: Reviewed, conflicts resolved

#92 Us 13 adm testi controller delete
  src/Controller/TestimoniesController.php
Labels: Reviewed, conflicts resolved

#108 S3 us11 services edit form
  public/assets/css/formService.css
  src/Controller/AdminController.php
  src/View/Admin/Home/Component/_form_service.html.twig
  src/View/Admin/Services/edit_service.html.twig
Labels: Corrections done, Reviewed

#121 fixing before PR to Master
  public/assets/css/contact.css
  public/assets/css/formService.css
  src/View/Admin/Home/Component/_admin_navbar.html.twig
  src/View/Admin/Home/Component/_form_service.html.twig
  src/View/Admin/Home/index.html.twig
  src/View/Visitor/Contact/contact.html.twig
  src/View/Visitor/History/index.html.twig
Labels: Reviewed

#122 PR dev to master S3 V1
  public/assets/css/contact.css
  public/assets/css/footer.css
  public/assets/css/formService.css
  public/assets/css/history/indexHistory.css
  public/assets/css/indexHome.css
  public/assets/css/navbar.css
  public/assets/css/services.css
  public/assets/css/style.css
  public/assets/css/success.css
  public/assets/css/testimony.css
  public/assets/css/training.css
  public/assets/images/culture.jpg
  public/assets/images/esprits.jpg
  public/assets/images/favicon_old.png
  public/assets/images/history/30ans.webp
  public/assets/images/history/42ans.jpg
  public/assets/images/history/8ans.webp
  public/assets/images/history/9-20ans.webp
  public/assets/images/magie.jpg
  public/assets/images/protection.jpg
  service.sql
  src/Controller/AdminController.php
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/Controller/TestimoniesController.php
  src/Controller/TrainingController.php
  src/Model/ServicesManager.php
  src/Model/TestimoniesManager.php
  src/Service/FormValidation.php
  src/View/Admin/Home/Component/_admin_navbar.html.twig
  src/View/Admin/Home/Component/_form_service.html.twig
  src/View/Admin/Home/index.html.twig
  src/View/Admin/Services/edit_service.html.twig
  src/View/Admin/admin_layout.html.twig
  src/View/Home/_prestations.html.twig
  src/View/Home/index.html.twig
  src/View/Visitor/Contact/contact.html.twig
  src/View/Visitor/Contact/success.html.twig
  src/View/Visitor/History/index.html.twig
  src/View/Visitor/Home/Component/_carousel.html.twig
  src/View/Visitor/Home/Component/_footer.html.twig
  src/View/Visitor/Home/Component/_home.html.twig
  src/View/Visitor/Home/Component/_navbar.html.twig
  src/View/Visitor/Home/Component/_services.html.twig
  src/View/Visitor/Home/Component/_story.html.twig
  src/View/Visitor/Home/index.html.twig
  src/View/Visitor/Training/index.html.twig
  src/View/Visitor/layout.html.twig
  src/View/base_layout.html.twig
  src/View/layout.html.twig
  testimony.sql
Labels: Reviewed

#110 S03_US4 - ADMIN - List services
  public/assets/css/services.css
  public/assets/css/style.css
  src/Controller/AdminController.php
  src/View/Admin/Home/Component/_admin_services.html.twig
  src/View/Admin/Home/index.html.twig
Labels: Reviewed

#109 US17_sendmail
  service.sql
  src/Controller/ContactController.php
Labels: Corrections done, Reviewed

#111 prestation edit and update
  src/Controller/AdminController.php
  src/Model/ServicesManager.php
Labels: changes requested

#123 update admin navbar links
  src/View/Admin/Home/Component/_admin_navbar.html.twig
Labels: Reviewed

#124 S03_US4 - ADMIN Fix links in services
  src/View/Admin/Home/Component/_admin_services.html.twig
Labels: Reviewed

#112 S3 us12 services add form
  public/assets/css/formservice.css
  src/Controller/AdminController.php
  src/View/Admin/Home/Component/_form_service.html.twig
  src/View/Admin/Services/add_service.html.twig
Labels: Reviewed, conflicts resolved

#114 US13_adm_testimony_index v2
  src/Controller/AdminController.php
  src/Controller/TestimoniesController.php
Labels: Reviewed, conflicts resolved

#125 S03_US4 - Service.sql DB
  service.sql
Labels: Reviewed

#118 Us13 adm services delete
  src/Controller/AdminController.php
Labels: Reviewed, conflicts resolved

#119 Us13 adm services add
  src/Controller/AdminController.php
  src/Model/ServicesManager.php
Labels: Reviewed, conflicts resolved

#135 S03 - dump.sql DB
  dump.sql
  service.sql
Labels: Reviewed

#126 Devfix before master
  public/assets/css/formService.css
  public/assets/css/formservice.css
  public/assets/css/style.css
  src/Controller/AdminController.php
  src/Model/ServicesManager.php
  src/View/Admin/Home/Component/_admin_navbar.html.twig
  src/View/Admin/Home/Component/_admin_services.html.twig
  src/View/Admin/Home/Component/_form_service.html.twig
  src/View/Admin/Services/add_service.html.twig
  src/View/Admin/Services/edit_service.html.twig
Labels: Reviewed
