Repository WildCodeSchool/orleans-php-202103-project-voyante, pull requests merged in 2021-05, with the labels that each got.

#148 correction done
  src/View/Visitor/History/index.html.twig
  src/View/Visitor/Home/Component/_story.html.twig
  src/View/Visitor/Training/index.html.twig
Labels: Reviewed

#147 deletetestimony in admin controller
  src/Controller/AdminController.php
Labels: Reviewed

#153 S04_US20 - ADMIN Services, secured delete button
  public/assets/css/services.css
  src/Controller/AdminController.php
  src/View/Admin/Home/Component/_admin_services.html.twig
Labels: Reviewed

#146 S03 us16 admin testimony list
  public/assets/css/admin_testimony.css
  src/View/Admin/Home/Component/_admin_testimony.html.twig
  src/View/Admin/Home/index.html.twig
Labels: Reviewed, conflicts resolved

#157 correcting redirection after deleting testimony
  src/Controller/AdminController.php
Labels: Reviewed

#155 S4 us22 aesthetic
  public/assets/css/indexHome.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  src/View/Admin/Home/Component/_admin_navbar.html.twig
  src/View/Visitor/Home/Component/_navbar.html.twig
Labels: Reviewed

#159 S04_US23 - Coherence story with training
  public/assets/css/history/indexHistory.css
  public/assets/images/history/30ans.jpg
  public/assets/images/history/30ans.webp
  public/assets/images/history/9-20ans.jpg
  public/assets/images/history/9-20ans.webp
  src/View/Visitor/History/index.html.twig
Labels: Reviewed

#158 Us19 carousel testimony
  public/assets/css/testimony.css
  src/Controller/ContactController.php
  src/View/Visitor/Home/Component/_carousel.html.twig
Labels: Reviewed, conflicts resolved

#160 changing background color
  public/assets/css/style.css
  public/assets/images/telephone.png
Labels: Reviewed

#149 Us25 esthetique qui suis je
  public/assets/css/indexStory.css
  src/View/Visitor/Home/Component/_story.html.twig
Labels: Reviewed

#154 S4 us17 add testimony form
  src/Controller/TestimonyController.php
  src/Model/TestimoniesManager.php
  src/View/Visitor/addTestimony/index.html.twig
Labels: Corrections done, Reviewed

#164 fixing the width problem
  public/assets/css/footer.css
  public/assets/css/style.css
  public/assets/css/testimony.css
Labels: Reviewed

#163 correcting story height
  public/assets/css/indexStory.css
  public/assets/css/style.css
Labels: Reviewed

#162 Devpatch links to contact
  public/assets/css/footer.css
  src/View/Visitor/Home/Component/_footer.html.twig
  src/View/Visitor/Home/Component/_home.html.twig
Labels: Reviewed

#165 Testimony style proposition
  public/assets/css/style.css
  public/assets/css/testimony.css
  src/View/Visitor/Home/Component/_carousel.html.twig
Labels: Reviewed, conflicts resolved

#166 modif testimonyStatus for validate testimony
  src/Controller/AdminController.php
  src/Model/TestimoniesManager.php
  src/View/Admin/Home/Component/_admin_testimony.html.twig
Labels: Corrections done, Reviewed

#167 US19 boucle testimony on carousel
  public/assets/css/testimony.css
  src/Controller/HomeController.php
  src/View/Visitor/Home/Component/_carousel.html.twig
Labels: Reviewed, conflicts resolved

#171 S04_US30 - Form button aesthetic
  public/assets/css/contact.css
  public/assets/css/formService.css
  public/assets/css/style.css
Labels: Reviewed

#173 S04_US28 - Added phone number to contact form
  public/assets/css/contact.css
  public/assets/css/style.css
  public/assets/images/phone-form.png
  src/View/Visitor/Contact/contact.html.twig
Labels: Reviewed

#176 S4_US31_UP_BUTTON
  public/assets/css/style.css
  src/View/base_layout.html.twig
Labels: Reviewed

#174 S04_US29 : Not mandatory inputs specified
  src/View/Admin/Home/Component/_form_service.html.twig
Labels: Corrections done, Reviewed

#180 get value on error on contact form
  src/Controller/ContactController.php
  src/View/Visitor/Contact/contact.html.twig
Labels: Reviewed

#179 S04_US34 - Uniformity of purple buttons
  public/assets/css/contact.css
  public/assets/css/formService.css
  public/assets/css/indexHome.css
  src/View/Visitor/Home/Component/_home.html.twig
Labels: Reviewed

#181 fixed accents in the navbar and added the id in the admin navbar to p…
  src/View/Admin/Home/Component/_admin_navbar.html.twig
  src/View/Visitor/Home/Component/_navbar.html.twig
Labels: Reviewed

#184 Purple buttons aesthetic and story font size changed
  public/assets/css/contact.css
  public/assets/css/formService.css
  public/assets/css/indexHome.css
  public/assets/css/indexStory.css
  public/assets/css/style.css
Labels: Reviewed

#186 Us16 securisation
  public/assets/css/style.css
  src/Controller/AdminController.php
Labels: Reviewed

#188 correcting admin navabr links
  src/View/Admin/Home/Component/_admin_navbar.html.twig
Labels: Reviewed

#183 filter testimonies: twig index + adminController index + methode test…
  src/Controller/AdminController.php
  src/Model/TestimoniesManager.php
  src/View/Admin/Home/Component/_admin_testimony.html.twig
Labels: Corrections done, Reviewed

#189 correcting admin navbar links
  src/View/Admin/Home/Component/_admin_navbar.html.twig
Labels: Reviewed

#190 Errors style
  public/assets/css/style.css
  src/View/Admin/Home/Component/_form_service.html.twig
  src/View/Visitor/Contact/contact.html.twig
  src/View/Visitor/addTestimony/index.html.twig
Labels: Reviewed

#191 S04_US35 - Aesthetict contact footer
  public/assets/css/footer.css
  public/assets/css/style.css
  src/View/Visitor/Home/Component/_footer.html.twig
Labels: Reviewed

#192 Maybe the last ?
  public/assets/css/admin_testimony.css
  public/assets/css/contact.css
  public/assets/css/footer.css
  public/assets/css/formService.css
  public/assets/css/history/indexHistory.css
  public/assets/css/indexHome.css
  public/assets/css/indexStory.css
  public/assets/css/navbar.css
  public/assets/css/services.css
  public/assets/css/style.css
  public/assets/css/testimony.css
  public/assets/images/history/30ans.jpg
  public/assets/images/history/30ans.webp
  public/assets/images/history/9-20ans.jpg
  public/assets/images/history/9-20ans.webp
  public/assets/images/phone-form.png
  public/assets/images/telephone.png
  src/Controller/AdminController.php
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/Controller/TestimonyController.php
  src/Model/TestimoniesManager.php
  src/View/Admin/Home/Component/_admin_navbar.html.twig
  src/View/Admin/Home/Component/_admin_services.html.twig
  src/View/Admin/Home/Component/_admin_testimony.html.twig
  src/View/Admin/Home/Component/_form_service.html.twig
  src/View/Admin/Home/index.html.twig
  src/View/Visitor/Contact/contact.html.twig
  src/View/Visitor/History/index.html.twig
  src/View/Visitor/Home/Component/_carousel.html.twig
  src/View/Visitor/Home/Component/_footer.html.twig
  src/View/Visitor/Home/Component/_home.html.twig
  src/View/Visitor/Home/Component/_navbar.html.twig
  src/View/Visitor/Home/Component/_story.html.twig
  src/View/Visitor/Training/index.html.twig
  src/View/Visitor/addTestimony/index.html.twig
  src/View/base_layout.html.twig
Labels: Reviewed

#194 Nathalie want a website
  public/assets/css/navbar.css
Labels: Reviewed

#212 select testimonies validate for visitor
  public/assets/css/style.css
  src/Controller/HomeController.php
Labels: Reviewed

#224 fix dump.sql file
  dump.sql
Labels: Reviewed

#227 fix change link h1 to navbar->accueil
  src/View/Visitor/Home/Component/_navbar.html.twig
Labels: Reviewed

#226 update the readme file
  README.md
Labels: Reviewed

#225 ISSUE - Removed arrow from forms
  public/assets/css/contact.css
  public/assets/css/formService.css
  src/View/base_layout.html.twig
Labels: Reviewed

#228 ISSUE - Corrected spelling mistakes
  src/View/Visitor/Contact/contact.html.twig
  src/View/Visitor/History/index.html.twig
Labels: Reviewed

#229 ISSUE - Corrected the pointer being on top of the arrow
  public/assets/css/training.css
Labels: Reviewed

#230 fix w3c
  src/View/Visitor/Home/Component/_footer.html.twig
  src/View/Visitor/addTestimony/index.html.twig
Labels: Reviewed

#231 ISSUE - Changed pointers
  public/assets/css/history/indexHistory.css
  public/assets/css/training.css
Labels: Reviewed

#233 Fix errors
  src/Controller/ContactController.php
Labels: Reviewed

#234 fix W3C
  src/View/Visitor/Training/index.html.twig
Labels: Reviewed

#235 Devpatch w3 c admin index
  public/assets/css/services.css
  src/View/Admin/Home/Component/_admin_services.html.twig
  src/View/Admin/Home/Component/_admin_testimony.html.twig
Labels: Reviewed

#236 fix issues on form: no id for for
  src/View/Admin/Home/Component/_form_service.html.twig
Labels: Reviewed

#237 fix /br to br
  src/View/Visitor/History/index.html.twig
Labels: Reviewed

#239 change responsive carousel
  public/assets/css/testimony.css
Labels: Reviewed

#238 fix w3c for home/index
  src/View/Visitor/Home/Component/_home.html.twig
  src/View/Visitor/Home/Component/_services.html.twig
  src/View/Visitor/Home/Component/_story.html.twig
Labels: Reviewed

#241 fix w3c of contact/index
  src/View/Visitor/Contact/contact.html.twig
Labels: Reviewed

#240 fixing background on phone image on contact
  public/assets/images/phone-form.png
Labels: Reviewed

#242 Fix select subject
  src/Controller/ContactController.php
  src/View/Visitor/Contact/contact.html.twig
Labels: Reviewed

#243 Fix to Master
  README.md
  dump.sql
  public/assets/css/contact.css
  public/assets/css/formService.css
  public/assets/css/history/indexHistory.css
  public/assets/css/services.css
  public/assets/css/style.css
  public/assets/css/testimony.css
  public/assets/css/training.css
  public/assets/images/phone-form.png
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/View/Admin/Home/Component/_admin_services.html.twig
  src/View/Admin/Home/Component/_admin_testimony.html.twig
  src/View/Admin/Home/Component/_form_service.html.twig
  src/View/Visitor/Contact/contact.html.twig
  src/View/Visitor/History/index.html.twig
  src/View/Visitor/Home/Component/_footer.html.twig
  src/View/Visitor/Home/Component/_home.html.twig
  src/View/Visitor/Home/Component/_navbar.html.twig
  src/View/Visitor/Home/Component/_services.html.twig
  src/View/Visitor/Home/Component/_story.html.twig
  src/View/Visitor/Training/index.html.twig
  src/View/Visitor/addTestimony/index.html.twig
  src/View/base_layout.html.twig
Labels: Reviewed

#244 interval slide
  src/View/Visitor/Home/Component/_carousel.html.twig
Labels: Reviewed
